info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  codegen:
    defaultPackage: wp.nandinwp
  profile: web
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
dataSources:
  dataSource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    url: jdbc:h2:mem:defaultDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  rj:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    url: jdbc:h2:mem:rjDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  mt:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    url: jdbc:h2:mem:mtDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  mg:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    url: jdbc:h2:mem:mgDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  es:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    url: jdbc:h2:mem:esDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
environments:
  development:
    dataSources:
      dataSource:
        dbCreate: update
        url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  test:
    dataSources:
      dataSource:
        dbCreate: update
        url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSources:
      dataSource:
        dbCreate: update
        url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      rj:
        dbCreate: update
        url: jdbc:h2:./rjDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      mt:
        dbCreate: update
        url: jdbc:h2:./mtDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      mg:
        dbCreate: update
        url: jdbc:h2:./mgDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      es:
        dbCreate: update
        url: jdbc:h2:./esDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
